--- #YAML:1.0
name: GPS-Lowrance-Trail
version: 0.43
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Convert between GDM16 Trails and other formats
license: perl
requires:
  Carp::Assert: 0
  FileHandle: 0
  Geo::Coordinates::DecimalDegrees: 0
  Geo::Coordinates::UTM: 0
  XML::Generator: 0
  perl: 5.6.1
provides: {}
generated_by: Module::Build version 0.24
